site_name: React Calendar

theme:
  icon:
      admonition:
        <type>: <icon> 
  name: readthedocs
  nav_style: light
  highlightjs: true
  hljs_languages:
        - javascript
  font:
    text: Roboto
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  extra_css: 
    -stylesheets/extra.css

plugins:
 - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences