site_name: React Calendar Documentation
nav:
  - Home: "index.md"
  - Setup Project: "pages/setup.md"
  - Project Structure: "pages/project-structure.md"
  - Styling: "pages/styling.md"
  - Event Listeners: "pages/eventlistener.md"
  - Glossary: "pages/glossary.md"

theme:
  name: material
  nav_style: light
  highlightjs: true
  hljs_languages:
    - javascript

  font:
    text: Roboto
    code: Roboto Mono
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  extra_css: 
  - stylesheets/extra.css

  extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/script.js
  
  # Necessary for search to work properly
include_search_page: false
search_index_only: true

plugins:
  - glightbox
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
