site_name: React Calendar

theme:
  name: material
  nav_style: light
  highlightjs: true
  hljs_languages:
    - javascript
  font:
    text: Roboto
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
  extra_css: -stylesheets/extra.css

  nav:
    - Section:
        - Home/index.md
    - Section:
        - Home/CRUD/create.md
        - Section:
          - Read Event: HOME/CRUD/read.md
          - Delete Event: HOME/CRUD/delete.md
        
        

plugins:
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
